### PR TITLE
Add predefined typescript types

### PR DESCRIPTION
**Pull request by sperezm97**
hi,

i just add support to generate `index.d.ts` in `dist` directory & set `types` in the package.json. 
This will enable autocomplete better in typescript projects.

### CODE REVIEW

**Comment by sperezm97** [comment]
@cla-bot chec

**Comment by sperezm97** [comment]
@cla-bot check

**Comment by sperezm97** [comment]
@cla-bot check

**Comment by kneth** [comment]
@sperezm97 
Thanks for your contribution. Please sign the [CLA](https://github.com/realm/realm-flipper-plugin/blob/main/documentation/CONTRIBUTING.md#cla).

**Comment by sperezm97** [comment]
i've tried multiple times and i didn't work  :(

@cla-bot check

**Comment by sperezm97** [comment]
we are ready to merge @kneth 🔥

**Review by kneth — APPROVED** [review]

**Pull request merged**
